server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: tumiao-picture-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tumiao_picture
    username: root
    password: 1234
mybatis-plus:
  configuration:
    # Mybatis-Plus 驼峰转下划线
    map-underscore-to-camel-case: false
    # 仅在开发环境打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的字段名
      logic-delete-field: isDelete
      # 逻辑已删除值（默认为1）
      logic-delete-value: 1
      # 逻辑未删除值（默认为0）
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xhtsoft.tumiaopicturebackend.controller